name: aki_datetime_picker
description: aki datetime picker is a versatile and user-friendly date and time picker component for web applications, designed to simplify date and time selection. With its intuitive interface and customizable options, it empowers developers to create seamless user experiences. Users can effortlessly pick dates, times, or both, while developers enjoy the flexibility to tailor its appearance and behavior to suit their specific needs. Whether for scheduling appointments, setting reminders, or managing events, this component streamlines the process, enhancing the overall functionality and aesthetic appeal of web applications.
version: 1.0.0
homepage: https://github.com/AKI-YU/aki_datetime_picker

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

repository: https://github.com/AKI-YU/aki_datetime_picker

topics:
  - datepicker
  - timepicker
  - datetimepicker
