name: aki_datetime_picker
description: A simple DateTime Picker made by AKI  
version: 1.0.0
homepage: https://github.com/AKI-YU/aki_datetime_picker

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

topics:
  - datepicker
  - timepicker
  - datetimepicker
